global:
  resolve_timeout: 1m

receivers:
  - name: 'telegram-webhook'
    webhook_configs:
      - url: 'http://telegram-bot:8000/alert'

route:
  group_by: ['alertname']
  receiver: 'telegram-webhook'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 15s
